### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot set property bytesRead of #<Socket> which has only a getter

### ISSUE THREAD

**Issue by Rene-Auberger** [pckhib/node-red-contrib-google#5]
I am running Node Red 1.0.3 with node-red-contrib-google-oauth2 to read events from a private Google calendar. Since 2-3 weeks this stopped working (might be correlated to the update of Node Red from 1.0.1 to 1.0.2). Oauth2 setup worked, Node Red is allowed to access Calendar API for my Google account. However, the google-node (API: "calendar:v3" and Operation: "events.list") fails with the following error:

`(node:26778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26778) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:26778) UnhandledPromiseRejectionWarning: TypeError: Cannot set property bytesRead of #<Socket> which has only a getter
    at _clone (/usr/lib/node_modules/node-red/node_modules/clone/clone.js:162:16)
    at _clone (/usr/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
    at clone (/usr/lib/node_modules/node-red/node_modules/clone/clone.js:202:10)
    at Object.cloneMessage (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:90:13)
    at GoogleNode.Node.send (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:409:61)
    at /home/auberger/.node-red/node_modules/node-red-contrib-google-oauth2/google.js:143:22
    at /home/auberger/.node-red/node_modules/googleapis-common/build/src/apirequest.js:49:53
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:26778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`

Can this be related to google-oauth2 using an outdated version of googleapi (36.0.0) instead of a recent version (45.0.0 is the latest as of this writing)?

**Comment by Rene-Auberger** [comment]
As this module seems to be unmaintained I meanwhile switched to node-red-contrib-ical-events as I needed the module only for Google Calendar. Querying using ical is even easier as no OAuth is needed.

**Comment by Hugobox** [comment]
See my pull request, it solved the problem in our flow. Basically since  node-red-contrib-google-oauth2 pipes the whole http response and request in msg.payload and they are not clonable objects. Node-Red will have this error as soon as the message goes through a branch (any node with 2 or more outgoing wires from an output) which as of Node-Red v1.0 now clones the object instead of referencing it. Another solution would be to move the unclonable parts to msg.req and msg.res (as these are excluded from cloning (see: https://github.com/node-red/node-red/blob/0ff324b0db65ed783897550b49adb736eca42beb/packages/node_modules/%40node-red/util/lib/util.js#L75-L100)

**Comment by pckhib** [comment]
Should be closed by #6 

If the problem still exists, let me know.

**Comment by Hugobox** [comment]
Thanks for merging the PR! Really appreciated! If you can publish the new version to NPM, it would be great for other Node-Red users! Thanks again!

**Comment by pckhib** [comment]
Thanks. Updated the version to 0.3.2 and published it on npm.
