### ISSUE TITLE
Could not receive tokens

### ISSUE THREAD

**Issue by mikewoodld** [pckhib/node-red-contrib-google#8]
Getting an error on the final step after clicking "allow" on the OAuth screen. Any ideas?

![image](https://user-images.githubusercontent.com/13637288/82135478-c73ae300-97c8-11ea-868f-4ecc5960fa21.png)

Trying to access the following scopes:
https://www.googleapis.com/auth/youtube
https://www.googleapis.com/auth/youtube.channel-memberships.creator
https://www.googleapis.com/auth/youtube.force-ssl
https://www.googleapis.com/auth/youtube.readonly
https://www.googleapis.com/auth/youtube.upload
https://www.googleapis.com/auth/youtubepartner
https://www.googleapis.com/auth/youtubepartner-channel-audit

**Comment by mikewoodld** [comment]
I'm not sure what I did wrong the first 10 times, but it's working now. I deleted and started from scratch.

**Comment by wmurray-es** [comment]
Same here, had this issue until I created new Oauth2 credentials in node-red

**Comment by pokryva** [comment]
Any hints what to pay attention to? I keep getting "Could not receive tokens" page during authentication process...
I created oAuth2 credentials in Google API Console, I enabled Gmail & Drive APIs, I tried the least restricted scopes (https://www.googleapis.com/auth/gmail.labels, https://www.googleapis.com/auth/drive.appdata). I tried starting from scratch few times already (deleting & creating new project in Google API Console, deleting & creating new oAuth credentials, rebooting NR what not).... Nothing works...

=== EDIT === 
After some struggles, maybe someone will find it helpful... I modified google-auth.js in line 95 to something like this: 
`return res.send('Could not receive tokens ' + error); `
this helped me to see what actually causes the error. In my case it was.... a now defunct proxy added as local system variable...

**Comment by bogorad** [comment]
> After some struggles, maybe someone will find it helpful... I modified google-auth.js in line 95 to something like this:
> `return res.send('Could not receive tokens ' + error); `

Followed your advice, and got this error:

> Could not receive tokens Error: invalid_client
